# Generated by Django 4.2.7 on 2025-07-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal Absensi')),
                ('jam_masuk', models.TimeField(blank=True, null=True, verbose_name='Jam Masuk')),
                ('jam_keluar', models.TimeField(blank=True, null=True, verbose_name='Jam Keluar')),
                ('status_kehadiran', models.CharField(choices=[('HADIR', 'Hadir'), ('IZIN', 'Izin'), ('SAKIT', 'Sakit'), ('ALPHA', 'Alpha')], max_length=20, verbose_name='Status Kehadiran')),
                ('keterangan', models.CharField(blank=True, max_length=255, verbose_name='Keterangan')),
            ],
            options={
                'verbose_name': 'Absensi',
                'verbose_name_plural': 'Data Absensi',
            },
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255, verbose_name='Judul Laporan')),
                ('file', models.FileField(upload_to='laporan_peserta/', verbose_name='File Laporan')),
                ('status_review', models.CharField(choices=[('BARU', 'Baru'), ('DIREVIEW', 'Direview'), ('DITERIMA', 'Diterima'), ('DITOLAK', 'Ditolak')], default='BARU', max_length=50, verbose_name='Status Review')),
                ('feedback_admin', models.TextField(blank=True, verbose_name='Feedback dari Admin')),
                ('disubmit_pada', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Submit')),
            ],
            options={
                'verbose_name': 'Laporan Peserta',
                'verbose_name_plural': 'Laporan Peserta',
            },
        ),
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Pendaftar')),
                ('nama_lengkap', models.CharField(max_length=255, verbose_name='Nama Lengkap')),
                ('tipe_peserta', models.CharField(choices=[('PELAJAR', 'Pelajar/Mahasiswa'), ('UMUM', 'Masyarakat Umum/Dinas')], max_length=50, verbose_name='Tipe Peserta')),
                ('nama_institusi', models.CharField(max_length=255, verbose_name='Nama Institusi')),
                ('no_telepon', models.CharField(max_length=20, verbose_name='No. Telepon/WA')),
                ('surat_pengajuan', models.FileField(upload_to='surat_pengajuan/', verbose_name='Surat Pengajuan')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Persetujuan'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak')], default='PENDING', max_length=50, verbose_name='Status Pendaftaran')),
                ('tanggal_daftar', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Daftar')),
            ],
            options={
                'verbose_name': 'Pendaftaran',
                'verbose_name_plural': 'Pendaftaran',
            },
        ),
        migrations.CreateModel(
            name='Penempatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, unique=True, verbose_name='Nama Unit Penempatan')),
                ('kuota_pelajar', models.PositiveIntegerField(default=10, verbose_name='Kuota Pelajar')),
                ('kuota_umum', models.PositiveIntegerField(default=5, verbose_name='Kuota Umum/Dinas')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi Singkat')),
            ],
            options={
                'verbose_name': 'Unit Penempatan',
                'verbose_name_plural': 'Unit Penempatan',
            },
        ),
        migrations.CreateModel(
            name='Sertifikat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_sertifikat', models.CharField(max_length=100, unique=True, verbose_name='Nomor Sertifikat')),
                ('file_sertifikat', models.FileField(upload_to='sertifikat/', verbose_name='File Sertifikat')),
                ('tanggal_terbit', models.DateField(verbose_name='Tanggal Terbit')),
                ('nilai_akhir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nilai Akhir')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikat',
            },
        ),
    ]
