# Generated by Django 4.2.7 on 2025-07-22 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bimbingan', '0001_initial'),
        ('peserta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sertifikat',
            name='profil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sertifikat', to='peserta.pesertaprofile'),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='pilihan_penempatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendaftaran', to='bimbingan.penempatan'),
        ),
    ]
