# Generated by Django 4.2.7 on 2025-07-22 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bimbingan', '0002_initial'),
        ('peserta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='user_terkait',
            field=models.OneToOneField(blank=True, help_text='Akun pengguna yang dibuat setelah pendaftaran disetujui.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laporan',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='peserta.pesertaprofile'),
        ),
        migrations.AddField(
            model_name='absensi',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi', to='peserta.pesertaprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='absensi',
            unique_together={('profil', 'tanggal')},
        ),
    ]
