# Generated by Django 4.2.7 on 2025-07-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimbingan', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absensi',
            options={'ordering': ['-tanggal'], 'verbose_name': 'Absensi', 'verbose_name_plural': 'Data Absensi'},
        ),
        migrations.AlterModelOptions(
            name='laporan',
            options={'ordering': ['-disubmit_pada'], 'verbose_name': 'Laporan Peserta', 'verbose_name_plural': 'Laporan Peserta'},
        ),
        migrations.AlterModelOptions(
            name='pendaftaran',
            options={'ordering': ['-tanggal_daftar'], 'verbose_name': 'Pendaftaran', 'verbose_name_plural': 'Data Pendaftaran'},
        ),
        migrations.AlterModelOptions(
            name='penempatan',
            options={'ordering': ['nama'], 'verbose_name': 'Unit Penempatan', 'verbose_name_plural': 'Unit Penempatan'},
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='email',
            field=models.EmailField(help_text='Pastikan email aktif untuk notifikasi.', max_length=254, unique=True, verbose_name='Email Pendaftar'),
        ),
    ]
