# Generated by Django 5.2.1 on 2025-08-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimbingan', '0004_alter_absensi_options_alter_laporan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='surat_dokter',
            field=models.FileField(blank=True, help_text='Upload surat dokter jika status sakit', null=True, upload_to='surat_dokter/', verbose_name='Surat Dokter'),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='keterangan',
            field=models.TextField(blank=True, help_text='Alasan untuk izin atau sakit', verbose_name='Keterangan'),
        ),
    ]
