# Generated by Django 5.2.1 on 2025-08-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimbingan', '0005_absensi_surat_dokter_alter_absensi_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='deskripsi',
            field=models.TextField(blank=True, help_text='Ringkasan singkat mengenai isi laporan.', verbose_name='Deskripsi/Ringkasan Laporan'),
        ),
    ]
