# Generated by Django 5.2.1 on 2025-08-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimbingan', '0006_laporan_deskripsi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sertifikat',
            options={'ordering': ['-tanggal_terbit'], 'verbose_name': 'Sertifikat', 'verbose_name_plural': 'Sertifikat'},
        ),
        migrations.AddField(
            model_name='sertifikat',
            name='template_digunakan',
            field=models.CharField(blank=True, choices=[('PELAJAR', 'Template Pelajar/Mahasiswa'), ('UMUM', 'Template Umum/Dinas')], max_length=20, verbose_name='Template yang Digunakan'),
        ),
        migrations.AlterField(
            model_name='sertifikat',
            name='tanggal_terbit',
            field=models.DateField(auto_now_add=True, verbose_name='Tanggal Terbit'),
        ),
    ]
