# Generated by Django 4.2.7 on 2025-08-15 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0008_alter_dokumen_jenis_dokumen'),
        ('bimbingan', '0007_alter_sertifikat_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('PENDAFTARAN', 'Pendaftaran'), ('LAPORAN', 'Laporan'), ('SERTIFIKAT', 'Sertifikat'), ('PENGUMUMAN', 'Pengumuman'), ('ABSENSI', 'Absensi')], max_length=20, verbose_name='Tipe Aktivitas')),
                ('pesan', models.TextField(verbose_name='Pesan Aktivitas')),
                ('tanggal', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktivitas', to='peserta.pesertaprofile')),
            ],
            options={
                'verbose_name': 'Aktivitas Peserta',
                'verbose_name_plural': 'Aktivitas Peserta',
                'ordering': ['-tanggal'],
            },
        ),
    ]
