# Generated by Django 4.2.7 on 2025-08-15 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bimbingan', '0008_aktivitas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aktivitas',
        ),
    ]
