# Generated by Django 5.2.1 on 2025-12-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimbingan', '0009_delete_aktivitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='email_pembimbing',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Pembimbing'),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='nama_pembimbing',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nama Pembimbing'),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='no_telepon_pembimbing',
            field=models.CharField(blank=True, max_length=20, verbose_name='No. Telepon Pembimbing'),
        ),
    ]
