# Generated by Django 4.2.7 on 2025-07-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255, verbose_name='Judul Pengumuman')),
                ('konten', models.TextField(verbose_name='Isi Pengumuman')),
                ('prioritas', models.CharField(choices=[('TINGGI', 'Tinggi'), ('SEDANG', 'Sedang'), ('RENDAH', 'Rendah')], default='SEDANG', max_length=20, verbose_name='Prioritas')),
                ('target_peserta', models.CharField(default='Semua Peserta', help_text='Contoh: Semua Peserta, Pelajar, Peserta Bioflok', max_length=50, verbose_name='Target Peserta')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('dipublish_pada', models.DateTimeField(blank=True, null=True, verbose_name='Dipublish Pada')),
            ],
            options={
                'verbose_name': 'Pengumuman',
                'verbose_name_plural': 'Pengumuman',
                'ordering': ['-dipublish_pada', '-dibuat_pada'],
            },
        ),
    ]
