# Generated by Django 4.2.7 on 2025-07-22 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pengumuman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumuman',
            name='penulis',
            field=models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengumuman', to=settings.AUTH_USER_MODEL),
        ),
    ]
