# Generated by Django 5.2.1 on 2025-08-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengumuman', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumuman',
            name='kategori',
            field=models.CharField(default='Umum', help_text='Contoh: Umum, Jadwal, Workshop', max_length=50, verbose_name='Kategori'),
        ),
    ]
