# Generated by Django 4.2.7 on 2025-07-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuktiPembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bukti_pembayaran/')),
                ('status_verifikasi', models.CharField(default='Menunggu Verifikasi', max_length=20)),
                ('diunggah_pada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_dokumen', models.CharField(help_text='Contoh: ktp, proposal', max_length=50)),
                ('file', models.FileField(upload_to='dokumen_peserta/')),
                ('diunggah_pada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PesertaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_peserta', models.CharField(choices=[('PELAJAR', 'Pelajar/Mahasiswa'), ('UMUM', 'Masyarakat Umum/Dinas')], max_length=50, verbose_name='Tipe Peserta')),
                ('alamat', models.TextField(blank=True, verbose_name='Alamat')),
                ('no_telepon', models.CharField(blank=True, max_length=20, verbose_name='No. Telepon/WA')),
                ('tempat_lahir', models.CharField(blank=True, max_length=100, verbose_name='Tempat Lahir')),
                ('tanggal_lahir', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('golongan_darah', models.CharField(blank=True, max_length=2, verbose_name='Golongan Darah')),
                ('nama_institusi', models.CharField(max_length=255, verbose_name='Nama Institusi')),
                ('alamat_institusi', models.TextField(blank=True, verbose_name='Alamat Institusi')),
                ('nomor_induk', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIM/NIS')),
                ('nama_pembimbing', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Pembimbing')),
            ],
        ),
    ]
