# Generated by Django 4.2.7 on 2025-07-22 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peserta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesertaprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='peserta.pesertaprofile'),
        ),
        migrations.AddField(
            model_name='buktipembayaran',
            name='profil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='peserta.pesertaprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='dokumen',
            unique_together={('profil', 'jenis_dokumen')},
        ),
    ]
