# Generated by Django 4.2.7 on 2025-07-22 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peserta', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buktipembayaran',
            options={'verbose_name': 'Bukti Pembayaran', 'verbose_name_plural': 'Bukti Pembayaran'},
        ),
        migrations.AlterModelOptions(
            name='dokumen',
            options={'verbose_name': 'Dokumen Peserta', 'verbose_name_plural': 'Dokumen Peserta'},
        ),
        migrations.AlterModelOptions(
            name='pesertaprofile',
            options={'verbose_name': 'Profil Peserta', 'verbose_name_plural': 'Profil Peserta'},
        ),
        migrations.RemoveField(
            model_name='pesertaprofile',
            name='alamat_institusi',
        ),
        migrations.RemoveField(
            model_name='pesertaprofile',
            name='golongan_darah',
        ),
        migrations.RemoveField(
            model_name='pesertaprofile',
            name='nama_pembimbing',
        ),
        migrations.RemoveField(
            model_name='pesertaprofile',
            name='nomor_induk',
        ),
        migrations.AddField(
            model_name='dokumen',
            name='status_verifikasi',
            field=models.CharField(default='Menunggu Verifikasi', max_length=50),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='dokumen_lengkap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='profil_lengkap',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buktipembayaran',
            name='profil',
            field=models.OneToOneField(limit_choices_to={'tipe_peserta': 'UMUM'}, on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='peserta.pesertaprofile'),
        ),
        migrations.AlterField(
            model_name='buktipembayaran',
            name='status_verifikasi',
            field=models.CharField(default='Menunggu Verifikasi', max_length=50),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='jenis_dokumen',
            field=models.CharField(help_text='Contoh: ktp, proposal, surat_pernyataan', max_length=100),
        ),
        migrations.AlterField(
            model_name='pesertaprofile',
            name='alamat',
            field=models.TextField(blank=True, verbose_name='Alamat Lengkap'),
        ),
        migrations.AlterField(
            model_name='pesertaprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_peserta', to=settings.AUTH_USER_MODEL),
        ),
    ]
