# Generated by Django 4.2.7 on 2025-07-23 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bimbingan', '0004_alter_absensi_options_alter_laporan_options_and_more'),
        ('peserta', '0003_alter_buktipembayaran_options_alter_dokumen_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesertaprofile',
            name='penempatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peserta', to='bimbingan.penempatan'),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='status',
            field=models.CharField(choices=[('AKTIF', 'Aktif'), ('SELESAI', 'Selesai'), ('LULUS', 'Lulus')], default='AKTIF', max_length=50, verbose_name='Status Peserta'),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='tanggal_mulai',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Mulai'),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='tanggal_selesai',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Selesai'),
        ),
    ]
