# Generated by Django 4.2.7 on 2025-07-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0004_pesertaprofile_penempatan_pesertaprofile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesertaprofile',
            name='alamat_institusi',
            field=models.TextField(blank=True, verbose_name='Alamat Institusi'),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='email_institusi',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Institusi'),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='email_pembimbing',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Pembimbing'),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='golongan_darah',
            field=models.CharField(blank=True, max_length=5, verbose_name='Golongan Darah'),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='nama_orang_tua',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nama Orang Tua'),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='nama_pembimbing',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nama Pembimbing'),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='no_telepon_institusi',
            field=models.CharField(blank=True, max_length=20, verbose_name='No. Telepon Institusi'),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='no_telepon_orang_tua',
            field=models.CharField(blank=True, max_length=20, verbose_name='No. Telepon Orang Tua'),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='no_telepon_pembimbing',
            field=models.CharField(blank=True, max_length=20, verbose_name='No. Telepon Pembimbing'),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='nomor_induk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nomor Induk Mahasiswa/Siswa'),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='penanganan_khusus',
            field=models.TextField(blank=True, verbose_name='Penanganan Khusus'),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='riwayat_penyakit',
            field=models.TextField(blank=True, verbose_name='Riwayat Penyakit'),
        ),
        migrations.AlterField(
            model_name='pesertaprofile',
            name='nama_institusi',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nama Institusi'),
        ),
    ]
