# Generated by Django 5.2.1 on 2025-07-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0005_pesertaprofile_alamat_institusi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesertaprofile',
            name='email_pembimbing',
        ),
        migrations.RemoveField(
            model_name='pesertaprofile',
            name='nama_pembimbing',
        ),
        migrations.RemoveField(
            model_name='pesertaprofile',
            name='no_telepon_institusi',
        ),
        migrations.RemoveField(
            model_name='pesertaprofile',
            name='no_telepon_pembimbing',
        ),
        migrations.RemoveField(
            model_name='pesertaprofile',
            name='nomor_induk',
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Email Pribadi'),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nama Lengkap'),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='penempatan_pkl',
            field=models.CharField(blank=True, max_length=255, verbose_name='Penempatan PKL'),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='rencana_akhir',
            field=models.DateField(blank=True, null=True, verbose_name='Rencana Akhir PKL'),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='rencana_mulai',
            field=models.DateField(blank=True, null=True, verbose_name='Rencana Mulai PKL'),
        ),
        migrations.AlterField(
            model_name='pesertaprofile',
            name='alamat_institusi',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alamat Institusi'),
        ),
        migrations.AlterField(
            model_name='pesertaprofile',
            name='email_institusi',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Email Institusi'),
        ),
        migrations.AlterField(
            model_name='pesertaprofile',
            name='nama_institusi',
            field=models.CharField(max_length=255, verbose_name='Nama Institusi'),
        ),
        migrations.AlterField(
            model_name='pesertaprofile',
            name='nama_orang_tua',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nama Orang Tua/Wali'),
        ),
        migrations.AlterField(
            model_name='pesertaprofile',
            name='no_telepon_orang_tua',
            field=models.CharField(blank=True, max_length=20, verbose_name='No. Telepon Orang Tua/Wali'),
        ),
    ]
