# Generated by Django 5.2.1 on 2025-07-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0006_remove_pesertaprofile_email_pembimbing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesertaprofile',
            name='email_pembimbing',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Email Pembimbing'),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='nama_pembimbing',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nama Pembimbing'),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='no_telepon_institusi',
            field=models.CharField(blank=True, max_length=30, verbose_name='No. Telepon Institusi'),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='no_telepon_pembimbing',
            field=models.CharField(blank=True, max_length=30, verbose_name='No. Telepon Pembimbing'),
        ),
        migrations.AddField(
            model_name='pesertaprofile',
            name='nomor_induk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nomor Induk Mahasiswa/Siswa'),
        ),
    ]
