# Generated by Django 5.2.1 on 2025-08-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0007_pesertaprofile_email_pembimbing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen',
            name='jenis_dokumen',
            field=models.CharField(help_text='Contoh: ktp, proposal, pernyataan', max_length=100),
        ),
    ]
