# Generated by Django 4.2.7 on 2025-08-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0008_alter_dokumen_jenis_dokumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='buktipembayaran',
            name='catatan_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan dari Admin'),
        ),
    ]
