# Generated by Django 4.2.7 on 2025-08-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0009_buktipembayaran_catatan_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buktipembayaran',
            name='status_verifikasi',
            field=models.CharField(choices=[('Menunggu Verifikasi', 'Menunggu Verifikasi'), ('Telah Diverifikasi', 'Telah Diverifikasi'), ('Ditolak', 'Ditolak')], default='Menunggu Verifikasi', max_length=50),
        ),
    ]
