# Generated by Django 4.2.7 on 2025-08-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0010_alter_buktipembayaran_status_verifikasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen',
            name='status_verifikasi',
            field=models.CharField(default='Telah Diverifikasi', max_length=50),
        ),
        migrations.AlterField(
            model_name='pesertaprofile',
            name='status',
            field=models.CharField(choices=[('Menunggu Kelengkapan Data', 'Menunggu Kelengkapan Data'), ('AKTIF', 'Aktif'), ('SELESAI', 'Selesai'), ('LULUS', 'Lulus')], default='Menunggu Kelengkapan Data', max_length=50, verbose_name='Status Peserta'),
        ),
    ]
