# Generated by Django 5.2.1 on 2025-12-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0011_alter_dokumen_status_verifikasi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesertaprofile',
            name='status',
            field=models.CharField(choices=[('AKTIF', 'Aktif'), ('SELESAI', 'Selesai'), ('LULUS', 'Lulus')], default='AKTIF', max_length=50, verbose_name='Status Peserta'),
        ),
    ]
